/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.bundesbank.jdemetra.exceladapter.options;

import de.bundesbank.jdemetra.exceladapter.handler.AbstractHandler;
import ec.util.list.swing.JListSelection;
import java.awt.BorderLayout;
import java.util.Enumeration;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import org.openide.util.Lookup;
import org.openide.util.NbPreferences;

final class ExcelAdapterPanel extends javax.swing.JPanel {

    private final ExcelAdapterOptionsPanelController controller;
    private final JListSelection<AbstractHandler> listSelection;

    ExcelAdapterPanel(ExcelAdapterOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        listSelection = new JListSelection();
        listSelection.setSourceHeader(new JLabel("Disabled"));
        listSelection.setTargetHeader(new JLabel("Enabled"));
        DefaultListModel<AbstractHandler> enabledModel = listSelection.getTargetModel();
        DefaultListModel<AbstractHandler> disabledModel = listSelection.getSourceModel();
        Lookup.getDefault().lookupAll(AbstractHandler.class)
                .forEach(handler -> {
                    if (handler.isEnabled()) {
                        enabledModel.addElement(handler);
                    } else {
                        disabledModel.addElement(handler);
                    }
                });

        jPanel1.add(listSelection, BorderLayout.CENTER);

        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
    }

    void store() {
        Enumeration<AbstractHandler> enabledHandler = listSelection.getTargetModel().elements();
        Enumeration<AbstractHandler> disabledHandler = listSelection.getSourceModel().elements();
        
        while (enabledHandler.hasMoreElements()) {
            AbstractHandler handler = enabledHandler.nextElement();
            NbPreferences.forModule(ExcelAdapterOptionsPanelController.class).putBoolean(handler.getOptionID(), true);
        }

        while (disabledHandler.hasMoreElements()) {
            AbstractHandler handler = disabledHandler.nextElement();
            NbPreferences.forModule(ExcelAdapterOptionsPanelController.class).putBoolean(handler.getOptionID(), false);
        }
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
